changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - refactor
        - ci
        - test
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
