settings:
  interactive_enabled: true
  show_banner: true
  list_table:
    columns:
    - name: task_name
      width: 40
    - name: priority
      width: 8
    - name: effort
      width: 6
    - name: created
      width: 10
    - name: deps
      width: 12
  task_body_sections:
  - name: Summary
    default: '- TODO'
  - name: Acceptance Criteria
    default: '- TODO'
